### PR TITLE
Added confusables.txt.

### PR DESCRIPTION
**Pull request by airbagy**

### CODE REVIEW

**Review by FrankYFTang — APPROVED** [review]
Wonderful Thanks. So with this, we may use the distance as threshold to cut more. for example, if I pick the threshold of 0.02 or 0.03 I think we will get some very close result.

**Comment by airbagy** [comment]
> Wonderful Thanks. So with this, we may use the distance as threshold to cut more. for example, if I pick the threshold of 0.02 or 0.03 I think we will get some very close result.

Yes. I agree!

**Comment by sffc** [comment]
Thank you!

**Comment by sffc** [comment]
I created https://unicode-org.atlassian.net/browse/ICU-21263 to follow up.

**Pull request merged**
